### ISSUE TITLE
Is this managed anymore?

### ISSUE THREAD

**Issue by stephenlacy** [mrrama/node-bunyan-prettystream#13]
Noticing the ever-increasing PR's list, and the last commit of 2 years ago, I am assuming that the owner of this project does not want to manage this anymore.

@mrrama do you want to continue development, or should I just publish my own with the proposed changes by the other collaborators?

**Comment by anoff** [comment]
@stevelacy I would support a clone with active PR management. I'd also like to contrib a feature to specify additional skippable elements that should not be shown in prettystream. However there is no use at this time to actually make a PR with the missing maintenance.

**Comment by cmawhorter** [comment]
From looking at the network graph it looks like the user @hadfieldn has done most of the work here over at [hadfieldn/node-bunyan-prettystream](https://github.com/hadfieldn/node-bunyan-prettystream).  Not sure if he's trying to make his stewardship official or not.  

FWIW -- I've been using this for over a year at least and have never had a problem with things as-is.

**Comment by jbcpollak** [comment]
I'm following this issue - we are adopting this. If there is a more active fork, please update this issue!

**Comment by ubershmekel** [comment]
This seems to be the most up to date fork with an npm package:
* https://github.com/MaximusHaximus/node-bunyan-prettystream
* https://www.npmjs.com/package/bunyan-prettystream-circularsafe
